<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <GenerateProgramFile>false</GenerateProgramFile>
  </PropertyGroup>
	<ItemGroup>
    <EmbeddedResource Include="resources\ATOMSequence.txt" />
    <EmbeddedResource Include="resources\Glucagon.txt" />
    <EmbeddedResource Include="resources\HasA.txt" />
    <EmbeddedResource Include="resources\HETATMSequence.txt" />
    <None Include="fixtures/**" CopyToOutputDirectory="Always" />
	<None Include="resources/**" CopyToOutputDirectory="Always" />
	<Compile Include="Utils.fs" />
    <Compile Include="ReferenceObjects\BioSeq.fs" />
    <Compile Include="ReferenceObjects\Fasta.fs" />
    <Compile Include="ReferenceObjects\Fastq.fs" />
    <Compile Include="ReferenceObjects\PDBParser.fs" />
    <Compile Include="ReferenceObjects\PDB.fs" />
    <Compile Include="ReferenceObjects\SASAanalysis.fs" />
    <Compile Include="Core\PairwiseAlignmentTests.fs" />
    <Compile Include="Core\AminoAcidTests.fs" />
    <Compile Include="Core\DigestionTests.fs" />
    <Compile Include="Core\NucleotideTests.fs" />
    <Compile Include="Core\BioSeq.fs" />
    <Compile Include="Core\BioArray.fs" />
    <Compile Include="Core\BioList.fs" />
    <Compile Include="Core\Isotopes.fs" />
    <Compile Include="Core\Elements.fs" />
    <Compile Include="Core\Formula.fs" />
    <Compile Include="Core\Mass.fs" />
    <Compile Include="Core\IBioItem.fs" />
    <Compile Include="Core\TaggedSequence.fs" />
    <Compile Include="Core\IsotopicDistribution.fs" />
    <Compile Include="Core\PhylTreeTests.fs" />
    <Compile Include="Core\Main.fs" />
    <Compile Include="FileFormats\Fasta.fs" />
    <Compile Include="FileFormats\Fastq.fs" />
    <Compile Include="FileFormats\Main.fs" />
    <Compile Include="IO\Fasta.fs" />
    <Compile Include="IO\Fastq.fs" />
    <Compile Include="IO\AgilentRaw.fs" />
    <Compile Include="IO\BlastQueries.fs" />
    <Compile Include="IO\CustomBlastResult.fs" />
    <Compile Include="IO\Clustal.fs" />
    <Compile Include="IO\DSSP.fs" />
    <Compile Include="IO\Stride.fs" />
    <Compile Include="IO\GAF.fs" />
    <Compile Include="IO\GenBank.fs" />
    <Compile Include="IO\GFF3.fs" />
    <Compile Include="IO\MGF.fs" />
    <Compile Include="IO\Newick.fs" />
    <Compile Include="IO\Obo.fs" />
    <Compile Include="IO\OrthoMCL.fs" />
    <Compile Include="IO\PDB.fs" />
    <Compile Include="IO\PDBParser.fs" />
    <Compile Include="IO\SOFT.fs" />
    <Compile Include="IO\Main.fs" />
	<Compile Include="Algorithm\SASAanalysis.fs" />
	<Compile Include="Algorithm\Main.fs" />
    <Compile Include="Main.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="altcover" Version="9.0.1" />
    <PackageReference Include="Expecto" Version="10.*" />
    <PackageReference Include="YoloDev.Expecto.TestSdk" Version="0.15.*" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.*" />
	<PackageReference Include="Deedle" Version="3.0.0" />
    <ProjectReference Include="..\..\src\BioFSharp\BioFSharp.fsproj" />
  </ItemGroup>

	

</Project>
